application: cs373-asn
version: 3
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py

- url: /ds.*
  script: importer.py

- url: /export.*
  script: exporter.py

- url: /.*
  script: asn.py
