application: cs373-asn2-awesome
version: 3
runtime: python
api_version: 1


handlers:
- url: /www
  static_dir: www

- url: /images
  static_dir: images

- url: /test.*
  script: gaeunit.py

- url: /selfdata.*
  script: ourData.py

- url: /tmp.*
  script: tmp.py

- url: /.*
  script: ASN1.py
