application: cs373-asn
version: 3
runtime: python
api_version: 1


handlers:
- url: /www
  static_dir: www

- url: /test.*
  script: gaeunit.py

- url: /selfdata.*
  script: ourData.py


- url: /.*
  script: ASN1.py
