application: cs373-asn
version: 3
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py

- url: /ds.*
  script: import.py

- url: /datastore.xml
  script: export.py

- url: /.*
  script: asn.py
